spring.application.name=validaya

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/validaya_db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=validayaadmin
spring.datasource.password=12345678
validaya.qr-code-expiration-time=30
server.port=8081

security.jwt.token.secret-key=K8O62/Fu2QBBxC1TiMfl+JseLgudPHuULCFJmQ4pQLA=
validaya.aes-secret-key=K8O62/Fu2QBBxC1TiMfl+JseLgudPHuULCFJmQ4pQLA=

stereum.callback-url=''
stereum.username=lucasvalcarce1@upb.edu
stereum.clave-integracion=j2upV83ds6uQdsappA1Al9LrAwOR0IwPk6b6cbmPjR0=
stereum.base-url=https://api.stereum.tech
stereum.connect-timeout=5000
stereum.read-timeout=10000
stereum.api-key=b2bf903a-f898-4d90-bc76-de878b10f098
stereum.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqi/vkOGgkREjky3g8SWixuh0EDFu08CPjgYVabAB9M44qp32VtqUb+X+hGgEk/nrsHC1QqfVbkDxEGyPjv0sM6qfPTlSior8kbwaJLWInbzh1Bfc8ILt2JcjGZZDpt2YFpCBJm9ZhUr6GQtXSjwi2iV4vrJbyH2Z+G2b132icJI0za5Rkr0je7SDCIEFnfJkTWbwcSzZHcjjwOYF60AZOsrMEVFQOpVF0mgp2OhJQoXUdIhEdrO+8BhsfaXNJt5gXWX0Lp1i+9OvS2lKnk9aCjver5WbyC3cBVutqif1aG3ay5SkWnruX0OMP3iXa5bfEkwwL0NhdbrQppF3CjjSgwIDAQAB\n-----END PUBLIC KEY-----
stereum.webhook-secret=your-webhook-secret-min-32-chars-random-string
stereum.max-retries=3
stereum.retry-delay=1000
stereum.webhook-max-age=300
stereum.default-currency=BOB
stereum.default-country=BO
stereum.default-network=POLYGON
stereum.default-blockchain-currency=USDT

security_jwt_token_expire-length=28800000

facial.recognition.api.url=http://localhost:5000