spring.application.name=validaya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

server.port=8080

security.jwt.token.secret-key=${JWT_SECRET_KEY}
validaya.aes-secret-key=${AES_SECRET_KEY}

validaya.qr-code-expiration-time=${QR_EXPIRATION_TIME}

# Configuración stereum
stereum.callback-url=${STEREUM_CALLBACK_URL}
stereum.username=${STEREUM_USER}
stereum.clave-integracion=${STEREUM_CLAVE}
stereum.base-url=${STEREUM_URL}
stereum.connect-timeout=${STEREUM_CONNECT_TIMEOUT}
stereum.read-timeout=${STEREUM_READ_TIMEOUT}
stereum.api-key=${STEREUM_API_KEY}
stereum.public-key=${STEREUM_PUBLIC_KEY}

stereum.max-retries=${STEREUM_MAX_RETRIES}
stereum.retry-delay=${STEREUM_RETRY_DELAY}
stereum.webhook-max-age=${STEREUM_WEBHOOK_MAX_AGE}

stereum.default-currency=${STEREUM_DEFAULT_CURRENCY}
stereum.default-country=${STEREUM_DEFAULT_COUNTRY}
stereum.default-network=${STEREUM_DEFAULT_NETWORK}
stereum.default-blockchain-currency=${STEREUM_DEFAULT_BLOCKCHAIN_CURRENCY}

stereum.tester-enabled={STEREUM.TESTER_ENABLED}

security_jwt_token_expire-length=${JWT_EXPIRE_LENGTH}

facial.recognition.api.url=${FACIAL_RECOGNITION_URL}